### ISSUE TITLE
Incorrect variable referenced in example

### ISSUE THREAD

**Issue by Socjon** [learn-co-curriculum/dsc-2-14-10-introduction-to-gradient-descent#1]
> Setting $m$ to 54 produced a lower error than at 54.550.  We kept moving our $b$ value lower until we set $m$ = 52, at which point our error began to increase.  Therefore, we know that **a value of $b$ between 52 and 53** produces the smallest RSS for our data **while $b = 1.319$.**

The first bold section should reference $m$, as $m$ is the slope.

**Comment by fpolchow** [comment]
fixed. thanks for flagging!
